context:
  version: "0.4.27"

package:
  name: flyctl
  version: ${{ version }}

source:
  git: https://github.com/superfly/flyctl.git
  tag: v${{ version }}
  depth: 1
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --ignore github.com/in-toto/in-toto-golang --ignore github.com/jmespath/go-jmespath --ignore github.com/launchdarkly/go-jsonstream/v3 --ignore github.com/launchdarkly/go-sdk-common/v3 --save_path ../library_licenses
    - if: unix
      then:
        - FLYCTL_COMMIT=$(git rev-parse --short HEAD)
        - FLYCTL_BUILD_DATE=$(git log -1 --format=%cI)
        - go build -v -o $PREFIX/bin/flyctl -ldflags="-s -w -X github.com/superfly/flyctl/internal/buildinfo.buildDate=$FLYCTL_BUILD_DATE -X github.com/superfly/flyctl/internal/buildinfo.buildVersion=${{ version }} -X github.com/superfly/flyctl/internal/buildinfo.commit=$FLYCTL_COMMIT" -tags production .
        - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
        - $PREFIX/bin/flyctl completion zsh > $PREFIX/share/zsh/site-functions/_flyctl
        - $PREFIX/bin/flyctl completion bash > $PREFIX/share/bash-completion/completions/flyctl
        - $PREFIX/bin/flyctl completion fish > $PREFIX/share/fish/vendor_completions.d/flyctl.fish
      else:
        - git rev-parse --short HEAD > commit.txt
        - for /f %%i in (commit.txt) do set "FLYCTL_COMMIT=%%i"
        - git log -1 --format=%%cI > date.txt
        - for /f %%i in (date.txt) do set "FLYCTL_BUILD_DATE=%%i"
        - go build -v -o %LIBRARY_BIN%\flyctl.exe -ldflags="-s -w -X github.com/superfly/flyctl/internal/buildinfo.buildDate=%FLYCTL_BUILD_DATE% -X github.com/superfly/flyctl/internal/buildinfo.buildVersion=%PKG_VERSION% -X github.com/superfly/flyctl/internal/buildinfo.commit=%FLYCTL_COMMIT%" -tags production .

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - git

tests:
  - script:
      - flyctl help
      - flyctl version
  - package_contents:
      bin:
        - flyctl
      files:
        - if: unix
          then:
            - share/bash-completion/completions/flyctl
            - share/fish/vendor_completions.d/flyctl.fish
            - share/zsh/site-functions/_flyctl
      strict: true

about:
  homepage: https://fly.io
  summary: CLI tool for deploying and managing applications on Fly.io
  description: |
    flyctl is the command-line interface for Fly.io, the platform for
    deploying and running applications close to your users. Use flyctl
    to launch apps, manage deployments, scale machines, handle secrets,
    and much more.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/superfly/flyctl
  documentation: https://fly.io/docs/flyctl/

extra:
  recipe-maintainers:
    - salim-b
