context:
  version: "0.8.2"

package:
  name: air
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/air/archive/refs/tags/${{ version }}.tar.gz
  sha256: 2af13c1ce799a36b570920f47df89a9c5efb28646b706b08494ace5d13d903db

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: win
        then:
          - set CARGO_HOME=C:\.cargo # work around cargo/libgit2 Windows MAX_PATH (260 char) limitation, cf. https://github.com/libgit2/libgit2/blob/main/docs/win32-longpaths.md
          - cargo auditable install --no-track --locked --bins --all-features --root %LIBRARY_PREFIX% --path crates/air
        else:
          - cargo auditable install --no-track --locked --bins --all-features --root ${{ PREFIX }} --path crates/air
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses

tests:
  - script:
      - air --help
      - air --version
  - package_contents:
      bin:
        - air
      strict: true

about:
  homepage: https://posit-dev.github.io/air/
  repository: https://github.com/posit-dev/air
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An R formatter and language server
  description: |
    Air is an R formatter and language server, written in Rust.

extra:
  recipe-maintainers:
    - salim-b
